<?php
/**
 * Trait get_icons
 *
 * @since	0.1.0
 *
 * @package mkdo\ground_control
 */

namespace mkdo\ground_control;

/**
 * An array of icon ID's and Names from Font Awesome
 */
trait Helper_Get_Icons {

	/**
	 * Get Icons
	 *
	 * An array of icon ID's and Names from Font Awesome v4.7.
	 *
	 * @return array Icons
	 */
	public static function get_icons() {

		$icons = array();
		$icons[] = array( 'id' => 'glass' , 'name' => 'Glass' );
		$icons[] = array( 'id' => 'music' , 'name' => 'Music' );
		$icons[] = array( 'id' => 'search' , 'name' => 'Search' );
		$icons[] = array( 'id' => 'envelope-o' , 'name' => 'Envelope Outlined' );
		$icons[] = array( 'id' => 'heart' , 'name' => 'Heart' );
		$icons[] = array( 'id' => 'star' , 'name' => 'Star' );
		$icons[] = array( 'id' => 'star-o' , 'name' => 'Star Outlined' );
		$icons[] = array( 'id' => 'user' , 'name' => 'User' );
		$icons[] = array( 'id' => 'film' , 'name' => 'Film' );
		$icons[] = array( 'id' => 'th-large' , 'name' => 'th-large' );
		$icons[] = array( 'id' => 'th' , 'name' => 'th' );
		$icons[] = array( 'id' => 'th-list' , 'name' => 'th-list' );
		$icons[] = array( 'id' => 'check' , 'name' => 'Check' );
		$icons[] = array( 'id' => 'times' , 'name' => 'Times' );
		$icons[] = array( 'id' => 'search-plus' , 'name' => 'Search Plus' );
		$icons[] = array( 'id' => 'search-minus' , 'name' => 'Search Minus' );
		$icons[] = array( 'id' => 'power-off' , 'name' => 'Power Off' );
		$icons[] = array( 'id' => 'signal' , 'name' => 'signal' );
		$icons[] = array( 'id' => 'cog' , 'name' => 'cog' );
		$icons[] = array( 'id' => 'trash-o' , 'name' => 'Trash Outlined' );
		$icons[] = array( 'id' => 'home' , 'name' => 'home' );
		$icons[] = array( 'id' => 'file-o' , 'name' => 'File Outlined' );
		$icons[] = array( 'id' => 'clock-o' , 'name' => 'Clock Outlined' );
		$icons[] = array( 'id' => 'road' , 'name' => 'road' );
		$icons[] = array( 'id' => 'download' , 'name' => 'Download' );
		$icons[] = array( 'id' => 'arrow-circle-o-down' , 'name' => 'Arrow Circle Outlined Down' );
		$icons[] = array( 'id' => 'arrow-circle-o-up' , 'name' => 'Arrow Circle Outlined Up' );
		$icons[] = array( 'id' => 'inbox' , 'name' => 'inbox' );
		$icons[] = array( 'id' => 'play-circle-o' , 'name' => 'Play Circle Outlined' );
		$icons[] = array( 'id' => 'repeat' , 'name' => 'Repeat' );
		$icons[] = array( 'id' => 'refresh' , 'name' => 'refresh' );
		$icons[] = array( 'id' => 'list-alt' , 'name' => 'list-alt' );
		$icons[] = array( 'id' => 'lock' , 'name' => 'lock' );
		$icons[] = array( 'id' => 'flag' , 'name' => 'flag' );
		$icons[] = array( 'id' => 'headphones' , 'name' => 'headphones' );
		$icons[] = array( 'id' => 'volume-off' , 'name' => 'volume-off' );
		$icons[] = array( 'id' => 'volume-down' , 'name' => 'volume-down' );
		$icons[] = array( 'id' => 'volume-up' , 'name' => 'volume-up' );
		$icons[] = array( 'id' => 'qrcode' , 'name' => 'qrcode' );
		$icons[] = array( 'id' => 'barcode' , 'name' => 'barcode' );
		$icons[] = array( 'id' => 'tag' , 'name' => 'tag' );
		$icons[] = array( 'id' => 'tags' , 'name' => 'tags' );
		$icons[] = array( 'id' => 'book' , 'name' => 'book' );
		$icons[] = array( 'id' => 'bookmark' , 'name' => 'bookmark' );
		$icons[] = array( 'id' => 'print' , 'name' => 'print' );
		$icons[] = array( 'id' => 'camera' , 'name' => 'camera' );
		$icons[] = array( 'id' => 'font' , 'name' => 'font' );
		$icons[] = array( 'id' => 'bold' , 'name' => 'bold' );
		$icons[] = array( 'id' => 'italic' , 'name' => 'italic' );
		$icons[] = array( 'id' => 'text-height' , 'name' => 'text-height' );
		$icons[] = array( 'id' => 'text-width' , 'name' => 'text-width' );
		$icons[] = array( 'id' => 'align-left' , 'name' => 'align-left' );
		$icons[] = array( 'id' => 'align-center' , 'name' => 'align-center' );
		$icons[] = array( 'id' => 'align-right' , 'name' => 'align-right' );
		$icons[] = array( 'id' => 'align-justify' , 'name' => 'align-justify' );
		$icons[] = array( 'id' => 'list' , 'name' => 'list' );
		$icons[] = array( 'id' => 'outdent' , 'name' => 'Outdent' );
		$icons[] = array( 'id' => 'indent' , 'name' => 'Indent' );
		$icons[] = array( 'id' => 'video-camera' , 'name' => 'Video Camera' );
		$icons[] = array( 'id' => 'picture-o' , 'name' => 'Picture Outlined' );
		$icons[] = array( 'id' => 'pencil' , 'name' => 'pencil' );
		$icons[] = array( 'id' => 'map-marker' , 'name' => 'map-marker' );
		$icons[] = array( 'id' => 'adjust' , 'name' => 'adjust' );
		$icons[] = array( 'id' => 'tint' , 'name' => 'tint' );
		$icons[] = array( 'id' => 'pencil-square-o' , 'name' => 'Pencil Square Outlined' );
		$icons[] = array( 'id' => 'share-square-o' , 'name' => 'Share Square Outlined' );
		$icons[] = array( 'id' => 'check-square-o' , 'name' => 'Check Square Outlined' );
		$icons[] = array( 'id' => 'arrows' , 'name' => 'Arrows' );
		$icons[] = array( 'id' => 'step-backward' , 'name' => 'step-backward' );
		$icons[] = array( 'id' => 'fast-backward' , 'name' => 'fast-backward' );
		$icons[] = array( 'id' => 'backward' , 'name' => 'backward' );
		$icons[] = array( 'id' => 'play' , 'name' => 'play' );
		$icons[] = array( 'id' => 'pause' , 'name' => 'pause' );
		$icons[] = array( 'id' => 'stop' , 'name' => 'stop' );
		$icons[] = array( 'id' => 'forward' , 'name' => 'forward' );
		$icons[] = array( 'id' => 'fast-forward' , 'name' => 'fast-forward' );
		$icons[] = array( 'id' => 'step-forward' , 'name' => 'step-forward' );
		$icons[] = array( 'id' => 'eject' , 'name' => 'eject' );
		$icons[] = array( 'id' => 'chevron-left' , 'name' => 'chevron-left' );
		$icons[] = array( 'id' => 'chevron-right' , 'name' => 'chevron-right' );
		$icons[] = array( 'id' => 'plus-circle' , 'name' => 'Plus Circle' );
		$icons[] = array( 'id' => 'minus-circle' , 'name' => 'Minus Circle' );
		$icons[] = array( 'id' => 'times-circle' , 'name' => 'Times Circle' );
		$icons[] = array( 'id' => 'check-circle' , 'name' => 'Check Circle' );
		$icons[] = array( 'id' => 'question-circle' , 'name' => 'Question Circle' );
		$icons[] = array( 'id' => 'info-circle' , 'name' => 'Info Circle' );
		$icons[] = array( 'id' => 'crosshairs' , 'name' => 'Crosshairs' );
		$icons[] = array( 'id' => 'times-circle-o' , 'name' => 'Times Circle Outlined' );
		$icons[] = array( 'id' => 'check-circle-o' , 'name' => 'Check Circle Outlined' );
		$icons[] = array( 'id' => 'ban' , 'name' => 'ban' );
		$icons[] = array( 'id' => 'arrow-left' , 'name' => 'arrow-left' );
		$icons[] = array( 'id' => 'arrow-right' , 'name' => 'arrow-right' );
		$icons[] = array( 'id' => 'arrow-up' , 'name' => 'arrow-up' );
		$icons[] = array( 'id' => 'arrow-down' , 'name' => 'arrow-down' );
		$icons[] = array( 'id' => 'share' , 'name' => 'Share' );
		$icons[] = array( 'id' => 'expand' , 'name' => 'Expand' );
		$icons[] = array( 'id' => 'compress' , 'name' => 'Compress' );
		$icons[] = array( 'id' => 'plus' , 'name' => 'plus' );
		$icons[] = array( 'id' => 'minus' , 'name' => 'minus' );
		$icons[] = array( 'id' => 'asterisk' , 'name' => 'asterisk' );
		$icons[] = array( 'id' => 'exclamation-circle' , 'name' => 'Exclamation Circle' );
		$icons[] = array( 'id' => 'gift' , 'name' => 'gift' );
		$icons[] = array( 'id' => 'leaf' , 'name' => 'leaf' );
		$icons[] = array( 'id' => 'fire' , 'name' => 'fire' );
		$icons[] = array( 'id' => 'eye' , 'name' => 'Eye' );
		$icons[] = array( 'id' => 'eye-slash' , 'name' => 'Eye Slash' );
		$icons[] = array( 'id' => 'exclamation-triangle' , 'name' => 'Exclamation Triangle' );
		$icons[] = array( 'id' => 'plane' , 'name' => 'plane' );
		$icons[] = array( 'id' => 'calendar' , 'name' => 'calendar' );
		$icons[] = array( 'id' => 'random' , 'name' => 'random' );
		$icons[] = array( 'id' => 'comment' , 'name' => 'comment' );
		$icons[] = array( 'id' => 'magnet' , 'name' => 'magnet' );
		$icons[] = array( 'id' => 'chevron-up' , 'name' => 'chevron-up' );
		$icons[] = array( 'id' => 'chevron-down' , 'name' => 'chevron-down' );
		$icons[] = array( 'id' => 'retweet' , 'name' => 'retweet' );
		$icons[] = array( 'id' => 'shopping-cart' , 'name' => 'shopping-cart' );
		$icons[] = array( 'id' => 'folder' , 'name' => 'Folder' );
		$icons[] = array( 'id' => 'folder-open' , 'name' => 'Folder Open' );
		$icons[] = array( 'id' => 'arrows-v' , 'name' => 'Arrows Vertical' );
		$icons[] = array( 'id' => 'arrows-h' , 'name' => 'Arrows Horizontal' );
		$icons[] = array( 'id' => 'bar-chart' , 'name' => 'Bar Chart' );
		$icons[] = array( 'id' => 'twitter-square' , 'name' => 'Twitter Square' );
		$icons[] = array( 'id' => 'facebook-square' , 'name' => 'Facebook Square' );
		$icons[] = array( 'id' => 'camera-retro' , 'name' => 'camera-retro' );
		$icons[] = array( 'id' => 'key' , 'name' => 'key' );
		$icons[] = array( 'id' => 'cogs' , 'name' => 'cogs' );
		$icons[] = array( 'id' => 'comments' , 'name' => 'comments' );
		$icons[] = array( 'id' => 'thumbs-o-up' , 'name' => 'Thumbs Up Outlined' );
		$icons[] = array( 'id' => 'thumbs-o-down' , 'name' => 'Thumbs Down Outlined' );
		$icons[] = array( 'id' => 'star-half' , 'name' => 'star-half' );
		$icons[] = array( 'id' => 'heart-o' , 'name' => 'Heart Outlined' );
		$icons[] = array( 'id' => 'sign-out' , 'name' => 'Sign Out' );
		$icons[] = array( 'id' => 'linkedin-square' , 'name' => 'LinkedIn Square' );
		$icons[] = array( 'id' => 'thumb-tack' , 'name' => 'Thumb Tack' );
		$icons[] = array( 'id' => 'external-link' , 'name' => 'External Link' );
		$icons[] = array( 'id' => 'sign-in' , 'name' => 'Sign In' );
		$icons[] = array( 'id' => 'trophy' , 'name' => 'trophy' );
		$icons[] = array( 'id' => 'github-square' , 'name' => 'GitHub Square' );
		$icons[] = array( 'id' => 'upload' , 'name' => 'Upload' );
		$icons[] = array( 'id' => 'lemon-o' , 'name' => 'Lemon Outlined' );
		$icons[] = array( 'id' => 'phone' , 'name' => 'Phone' );
		$icons[] = array( 'id' => 'square-o' , 'name' => 'Square Outlined' );
		$icons[] = array( 'id' => 'bookmark-o' , 'name' => 'Bookmark Outlined' );
		$icons[] = array( 'id' => 'phone-square' , 'name' => 'Phone Square' );
		$icons[] = array( 'id' => 'twitter' , 'name' => 'Twitter' );
		$icons[] = array( 'id' => 'facebook' , 'name' => 'Facebook' );
		$icons[] = array( 'id' => 'github' , 'name' => 'GitHub' );
		$icons[] = array( 'id' => 'unlock' , 'name' => 'unlock' );
		$icons[] = array( 'id' => 'credit-card' , 'name' => 'credit-card' );
		$icons[] = array( 'id' => 'rss' , 'name' => 'rss' );
		$icons[] = array( 'id' => 'hdd-o' , 'name' => 'HDD' );
		$icons[] = array( 'id' => 'bullhorn' , 'name' => 'bullhorn' );
		$icons[] = array( 'id' => 'bell' , 'name' => 'bell' );
		$icons[] = array( 'id' => 'certificate' , 'name' => 'certificate' );
		$icons[] = array( 'id' => 'hand-o-right' , 'name' => 'Hand Outlined Right' );
		$icons[] = array( 'id' => 'hand-o-left' , 'name' => 'Hand Outlined Left' );
		$icons[] = array( 'id' => 'hand-o-up' , 'name' => 'Hand Outlined Up' );
		$icons[] = array( 'id' => 'hand-o-down' , 'name' => 'Hand Outlined Down' );
		$icons[] = array( 'id' => 'arrow-circle-left' , 'name' => 'Arrow Circle Left' );
		$icons[] = array( 'id' => 'arrow-circle-right' , 'name' => 'Arrow Circle Right' );
		$icons[] = array( 'id' => 'arrow-circle-up' , 'name' => 'Arrow Circle Up' );
		$icons[] = array( 'id' => 'arrow-circle-down' , 'name' => 'Arrow Circle Down' );
		$icons[] = array( 'id' => 'globe' , 'name' => 'Globe' );
		$icons[] = array( 'id' => 'wrench' , 'name' => 'Wrench' );
		$icons[] = array( 'id' => 'tasks' , 'name' => 'Tasks' );
		$icons[] = array( 'id' => 'filter' , 'name' => 'Filter' );
		$icons[] = array( 'id' => 'briefcase' , 'name' => 'Briefcase' );
		$icons[] = array( 'id' => 'arrows-alt' , 'name' => 'Arrows Alt' );
		$icons[] = array( 'id' => 'users' , 'name' => 'Users' );
		$icons[] = array( 'id' => 'link' , 'name' => 'Link' );
		$icons[] = array( 'id' => 'cloud' , 'name' => 'Cloud' );
		$icons[] = array( 'id' => 'flask' , 'name' => 'Flask' );
		$icons[] = array( 'id' => 'scissors' , 'name' => 'Scissors' );
		$icons[] = array( 'id' => 'files-o' , 'name' => 'Files Outlined' );
		$icons[] = array( 'id' => 'paperclip' , 'name' => 'Paperclip' );
		$icons[] = array( 'id' => 'floppy-o' , 'name' => 'Floppy Outlined' );
		$icons[] = array( 'id' => 'square' , 'name' => 'Square' );
		$icons[] = array( 'id' => 'bars' , 'name' => 'Bars' );
		$icons[] = array( 'id' => 'list-ul' , 'name' => 'list-ul' );
		$icons[] = array( 'id' => 'list-ol' , 'name' => 'list-ol' );
		$icons[] = array( 'id' => 'strikethrough' , 'name' => 'Strikethrough' );
		$icons[] = array( 'id' => 'underline' , 'name' => 'Underline' );
		$icons[] = array( 'id' => 'table' , 'name' => 'table' );
		$icons[] = array( 'id' => 'magic' , 'name' => 'magic' );
		$icons[] = array( 'id' => 'truck' , 'name' => 'truck' );
		$icons[] = array( 'id' => 'pinterest' , 'name' => 'Pinterest' );
		$icons[] = array( 'id' => 'pinterest-square' , 'name' => 'Pinterest Square' );
		$icons[] = array( 'id' => 'google-plus-square' , 'name' => 'Google Plus Square' );
		$icons[] = array( 'id' => 'google-plus' , 'name' => 'Google Plus' );
		$icons[] = array( 'id' => 'money' , 'name' => 'Money' );
		$icons[] = array( 'id' => 'caret-down' , 'name' => 'Caret Down' );
		$icons[] = array( 'id' => 'caret-up' , 'name' => 'Caret Up' );
		$icons[] = array( 'id' => 'caret-left' , 'name' => 'Caret Left' );
		$icons[] = array( 'id' => 'caret-right' , 'name' => 'Caret Right' );
		$icons[] = array( 'id' => 'columns' , 'name' => 'Columns' );
		$icons[] = array( 'id' => 'sort' , 'name' => 'Sort' );
		$icons[] = array( 'id' => 'sort-desc' , 'name' => 'Sort Descending' );
		$icons[] = array( 'id' => 'sort-asc' , 'name' => 'Sort Ascending' );
		$icons[] = array( 'id' => 'envelope' , 'name' => 'Envelope' );
		$icons[] = array( 'id' => 'linkedin' , 'name' => 'LinkedIn' );
		$icons[] = array( 'id' => 'undo' , 'name' => 'Undo' );
		$icons[] = array( 'id' => 'gavel' , 'name' => 'Gavel' );
		$icons[] = array( 'id' => 'tachometer' , 'name' => 'Tachometer' );
		$icons[] = array( 'id' => 'comment-o' , 'name' => 'comment-o' );
		$icons[] = array( 'id' => 'comments-o' , 'name' => 'comments-o' );
		$icons[] = array( 'id' => 'bolt' , 'name' => 'Lightning Bolt' );
		$icons[] = array( 'id' => 'sitemap' , 'name' => 'Sitemap' );
		$icons[] = array( 'id' => 'umbrella' , 'name' => 'Umbrella' );
		$icons[] = array( 'id' => 'clipboard' , 'name' => 'Clipboard' );
		$icons[] = array( 'id' => 'lightbulb-o' , 'name' => 'Lightbulb Outlined' );
		$icons[] = array( 'id' => 'exchange' , 'name' => 'Exchange' );
		$icons[] = array( 'id' => 'cloud-download' , 'name' => 'Cloud Download' );
		$icons[] = array( 'id' => 'cloud-upload' , 'name' => 'Cloud Upload' );
		$icons[] = array( 'id' => 'user-md' , 'name' => 'user-md' );
		$icons[] = array( 'id' => 'stethoscope' , 'name' => 'Stethoscope' );
		$icons[] = array( 'id' => 'suitcase' , 'name' => 'Suitcase' );
		$icons[] = array( 'id' => 'bell-o' , 'name' => 'Bell Outlined' );
		$icons[] = array( 'id' => 'coffee' , 'name' => 'Coffee' );
		$icons[] = array( 'id' => 'cutlery' , 'name' => 'Cutlery' );
		$icons[] = array( 'id' => 'file-text-o' , 'name' => 'File Text Outlined' );
		$icons[] = array( 'id' => 'building-o' , 'name' => 'Building Outlined' );
		$icons[] = array( 'id' => 'hospital-o' , 'name' => 'hospital Outlined' );
		$icons[] = array( 'id' => 'ambulance' , 'name' => 'ambulance' );
		$icons[] = array( 'id' => 'medkit' , 'name' => 'medkit' );
		$icons[] = array( 'id' => 'fighter-jet' , 'name' => 'fighter-jet' );
		$icons[] = array( 'id' => 'beer' , 'name' => 'beer' );
		$icons[] = array( 'id' => 'h-square' , 'name' => 'H Square' );
		$icons[] = array( 'id' => 'plus-square' , 'name' => 'Plus Square' );
		$icons[] = array( 'id' => 'angle-double-left' , 'name' => 'Angle Double Left' );
		$icons[] = array( 'id' => 'angle-double-right' , 'name' => 'Angle Double Right' );
		$icons[] = array( 'id' => 'angle-double-up' , 'name' => 'Angle Double Up' );
		$icons[] = array( 'id' => 'angle-double-down' , 'name' => 'Angle Double Down' );
		$icons[] = array( 'id' => 'angle-left' , 'name' => 'angle-left' );
		$icons[] = array( 'id' => 'angle-right' , 'name' => 'angle-right' );
		$icons[] = array( 'id' => 'angle-up' , 'name' => 'angle-up' );
		$icons[] = array( 'id' => 'angle-down' , 'name' => 'angle-down' );
		$icons[] = array( 'id' => 'desktop' , 'name' => 'Desktop' );
		$icons[] = array( 'id' => 'laptop' , 'name' => 'Laptop' );
		$icons[] = array( 'id' => 'tablet' , 'name' => 'tablet' );
		$icons[] = array( 'id' => 'mobile' , 'name' => 'Mobile Phone' );
		$icons[] = array( 'id' => 'circle-o' , 'name' => 'Circle Outlined' );
		$icons[] = array( 'id' => 'quote-left' , 'name' => 'quote-left' );
		$icons[] = array( 'id' => 'quote-right' , 'name' => 'quote-right' );
		$icons[] = array( 'id' => 'spinner' , 'name' => 'Spinner' );
		$icons[] = array( 'id' => 'circle' , 'name' => 'Circle' );
		$icons[] = array( 'id' => 'reply' , 'name' => 'Reply' );
		$icons[] = array( 'id' => 'github-alt' , 'name' => 'GitHub Alt' );
		$icons[] = array( 'id' => 'folder-o' , 'name' => 'Folder Outlined' );
		$icons[] = array( 'id' => 'folder-open-o' , 'name' => 'Folder Open Outlined' );
		$icons[] = array( 'id' => 'smile-o' , 'name' => 'Smile Outlined' );
		$icons[] = array( 'id' => 'frown-o' , 'name' => 'Frown Outlined' );
		$icons[] = array( 'id' => 'meh-o' , 'name' => 'Meh Outlined' );
		$icons[] = array( 'id' => 'gamepad' , 'name' => 'Gamepad' );
		$icons[] = array( 'id' => 'keyboard-o' , 'name' => 'Keyboard Outlined' );
		$icons[] = array( 'id' => 'flag-o' , 'name' => 'Flag Outlined' );
		$icons[] = array( 'id' => 'flag-checkered' , 'name' => 'flag-checkered' );
		$icons[] = array( 'id' => 'terminal' , 'name' => 'Terminal' );
		$icons[] = array( 'id' => 'code' , 'name' => 'Code' );
		$icons[] = array( 'id' => 'reply-all' , 'name' => 'reply-all' );
		$icons[] = array( 'id' => 'star-half-o' , 'name' => 'Star Half Outlined' );
		$icons[] = array( 'id' => 'location-arrow' , 'name' => 'location-arrow' );
		$icons[] = array( 'id' => 'crop' , 'name' => 'crop' );
		$icons[] = array( 'id' => 'code-fork' , 'name' => 'code-fork' );
		$icons[] = array( 'id' => 'chain-broken' , 'name' => 'Chain Broken' );
		$icons[] = array( 'id' => 'question' , 'name' => 'Question' );
		$icons[] = array( 'id' => 'info' , 'name' => 'Info' );
		$icons[] = array( 'id' => 'exclamation' , 'name' => 'exclamation' );
		$icons[] = array( 'id' => 'superscript' , 'name' => 'superscript' );
		$icons[] = array( 'id' => 'subscript' , 'name' => 'subscript' );
		$icons[] = array( 'id' => 'eraser' , 'name' => 'eraser' );
		$icons[] = array( 'id' => 'puzzle-piece' , 'name' => 'Puzzle Piece' );
		$icons[] = array( 'id' => 'microphone' , 'name' => 'microphone' );
		$icons[] = array( 'id' => 'microphone-slash' , 'name' => 'Microphone Slash' );
		$icons[] = array( 'id' => 'shield' , 'name' => 'shield' );
		$icons[] = array( 'id' => 'calendar-o' , 'name' => 'calendar-o' );
		$icons[] = array( 'id' => 'fire-extinguisher' , 'name' => 'fire-extinguisher' );
		$icons[] = array( 'id' => 'rocket' , 'name' => 'rocket' );
		$icons[] = array( 'id' => 'maxcdn' , 'name' => 'MaxCDN' );
		$icons[] = array( 'id' => 'chevron-circle-left' , 'name' => 'Chevron Circle Left' );
		$icons[] = array( 'id' => 'chevron-circle-right' , 'name' => 'Chevron Circle Right' );
		$icons[] = array( 'id' => 'chevron-circle-up' , 'name' => 'Chevron Circle Up' );
		$icons[] = array( 'id' => 'chevron-circle-down' , 'name' => 'Chevron Circle Down' );
		$icons[] = array( 'id' => 'html5' , 'name' => 'HTML 5 Logo' );
		$icons[] = array( 'id' => 'css3' , 'name' => 'CSS 3 Logo' );
		$icons[] = array( 'id' => 'anchor' , 'name' => 'Anchor' );
		$icons[] = array( 'id' => 'unlock-alt' , 'name' => 'Unlock Alt' );
		$icons[] = array( 'id' => 'bullseye' , 'name' => 'Bullseye' );
		$icons[] = array( 'id' => 'ellipsis-h' , 'name' => 'Ellipsis Horizontal' );
		$icons[] = array( 'id' => 'ellipsis-v' , 'name' => 'Ellipsis Vertical' );
		$icons[] = array( 'id' => 'rss-square' , 'name' => 'RSS Square' );
		$icons[] = array( 'id' => 'play-circle' , 'name' => 'Play Circle' );
		$icons[] = array( 'id' => 'ticket' , 'name' => 'Ticket' );
		$icons[] = array( 'id' => 'minus-square' , 'name' => 'Minus Square' );
		$icons[] = array( 'id' => 'minus-square-o' , 'name' => 'Minus Square Outlined' );
		$icons[] = array( 'id' => 'level-up' , 'name' => 'Level Up' );
		$icons[] = array( 'id' => 'level-down' , 'name' => 'Level Down' );
		$icons[] = array( 'id' => 'check-square' , 'name' => 'Check Square' );
		$icons[] = array( 'id' => 'pencil-square' , 'name' => 'Pencil Square' );
		$icons[] = array( 'id' => 'external-link-square' , 'name' => 'External Link Square' );
		$icons[] = array( 'id' => 'share-square' , 'name' => 'Share Square' );
		$icons[] = array( 'id' => 'compass' , 'name' => 'Compass' );
		$icons[] = array( 'id' => 'caret-square-o-down' , 'name' => 'Caret Square Outlined Down' );
		$icons[] = array( 'id' => 'caret-square-o-up' , 'name' => 'Caret Square Outlined Up' );
		$icons[] = array( 'id' => 'caret-square-o-right' , 'name' => 'Caret Square Outlined Right' );
		$icons[] = array( 'id' => 'eur' , 'name' => 'Euro (EUR)' );
		$icons[] = array( 'id' => 'gbp' , 'name' => 'GBP' );
		$icons[] = array( 'id' => 'usd' , 'name' => 'US Dollar' );
		$icons[] = array( 'id' => 'inr' , 'name' => 'Indian Rupee (INR)' );
		$icons[] = array( 'id' => 'jpy' , 'name' => 'Japanese Yen (JPY)' );
		$icons[] = array( 'id' => 'rub' , 'name' => 'Russian Ruble (RUB)' );
		$icons[] = array( 'id' => 'krw' , 'name' => 'Korean Won (KRW)' );
		$icons[] = array( 'id' => 'btc' , 'name' => 'Bitcoin (BTC)' );
		$icons[] = array( 'id' => 'file' , 'name' => 'File' );
		$icons[] = array( 'id' => 'file-text' , 'name' => 'File Text' );
		$icons[] = array( 'id' => 'sort-alpha-asc' , 'name' => 'Sort Alpha Ascending' );
		$icons[] = array( 'id' => 'sort-alpha-desc' , 'name' => 'Sort Alpha Descending' );
		$icons[] = array( 'id' => 'sort-amount-asc' , 'name' => 'Sort Amount Ascending' );
		$icons[] = array( 'id' => 'sort-amount-desc' , 'name' => 'Sort Amount Descending' );
		$icons[] = array( 'id' => 'sort-numeric-asc' , 'name' => 'Sort Numeric Ascending' );
		$icons[] = array( 'id' => 'sort-numeric-desc' , 'name' => 'Sort Numeric Descending' );
		$icons[] = array( 'id' => 'thumbs-up' , 'name' => 'thumbs-up' );
		$icons[] = array( 'id' => 'thumbs-down' , 'name' => 'thumbs-down' );
		$icons[] = array( 'id' => 'youtube-square' , 'name' => 'YouTube Square' );
		$icons[] = array( 'id' => 'youtube' , 'name' => 'YouTube' );
		$icons[] = array( 'id' => 'xing' , 'name' => 'Xing' );
		$icons[] = array( 'id' => 'xing-square' , 'name' => 'Xing Square' );
		$icons[] = array( 'id' => 'youtube-play' , 'name' => 'YouTube Play' );
		$icons[] = array( 'id' => 'dropbox' , 'name' => 'Dropbox' );
		$icons[] = array( 'id' => 'stack-overflow' , 'name' => 'Stack Overflow' );
		$icons[] = array( 'id' => 'instagram' , 'name' => 'Instagram' );
		$icons[] = array( 'id' => 'flickr' , 'name' => 'Flickr' );
		$icons[] = array( 'id' => 'adn' , 'name' => 'App.net' );
		$icons[] = array( 'id' => 'bitbucket' , 'name' => 'Bitbucket' );
		$icons[] = array( 'id' => 'bitbucket-square' , 'name' => 'Bitbucket Square' );
		$icons[] = array( 'id' => 'tumblr' , 'name' => 'Tumblr' );
		$icons[] = array( 'id' => 'tumblr-square' , 'name' => 'Tumblr Square' );
		$icons[] = array( 'id' => 'long-arrow-down' , 'name' => 'Long Arrow Down' );
		$icons[] = array( 'id' => 'long-arrow-up' , 'name' => 'Long Arrow Up' );
		$icons[] = array( 'id' => 'long-arrow-left' , 'name' => 'Long Arrow Left' );
		$icons[] = array( 'id' => 'long-arrow-right' , 'name' => 'Long Arrow Right' );
		$icons[] = array( 'id' => 'apple' , 'name' => 'Apple' );
		$icons[] = array( 'id' => 'windows' , 'name' => 'Windows' );
		$icons[] = array( 'id' => 'android' , 'name' => 'Android' );
		$icons[] = array( 'id' => 'linux' , 'name' => 'Linux' );
		$icons[] = array( 'id' => 'dribbble' , 'name' => 'Dribbble' );
		$icons[] = array( 'id' => 'skype' , 'name' => 'Skype' );
		$icons[] = array( 'id' => 'foursquare' , 'name' => 'Foursquare' );
		$icons[] = array( 'id' => 'trello' , 'name' => 'Trello' );
		$icons[] = array( 'id' => 'female' , 'name' => 'Female' );
		$icons[] = array( 'id' => 'male' , 'name' => 'Male' );
		$icons[] = array( 'id' => 'gratipay' , 'name' => 'Gratipay (Gittip)' );
		$icons[] = array( 'id' => 'sun-o' , 'name' => 'Sun Outlined' );
		$icons[] = array( 'id' => 'moon-o' , 'name' => 'Moon Outlined' );
		$icons[] = array( 'id' => 'archive' , 'name' => 'Archive' );
		$icons[] = array( 'id' => 'bug' , 'name' => 'Bug' );
		$icons[] = array( 'id' => 'vk' , 'name' => 'VK' );
		$icons[] = array( 'id' => 'weibo' , 'name' => 'Weibo' );
		$icons[] = array( 'id' => 'renren' , 'name' => 'Renren' );
		$icons[] = array( 'id' => 'pagelines' , 'name' => 'Pagelines' );
		$icons[] = array( 'id' => 'stack-exchange' , 'name' => 'Stack Exchange' );
		$icons[] = array( 'id' => 'arrow-circle-o-right' , 'name' => 'Arrow Circle Outlined Right' );
		$icons[] = array( 'id' => 'arrow-circle-o-left' , 'name' => 'Arrow Circle Outlined Left' );
		$icons[] = array( 'id' => 'caret-square-o-left' , 'name' => 'Caret Square Outlined Left' );
		$icons[] = array( 'id' => 'dot-circle-o' , 'name' => 'Dot Circle Outlined' );
		$icons[] = array( 'id' => 'wheelchair' , 'name' => 'Wheelchair' );
		$icons[] = array( 'id' => 'vimeo-square' , 'name' => 'Vimeo Square' );
		$icons[] = array( 'id' => 'try' , 'name' => 'Turkish Lira (TRY)' );
		$icons[] = array( 'id' => 'plus-square-o' , 'name' => 'Plus Square Outlined' );
		$icons[] = array( 'id' => 'space-shuttle' , 'name' => 'Space Shuttle' );
		$icons[] = array( 'id' => 'slack' , 'name' => 'Slack Logo' );
		$icons[] = array( 'id' => 'envelope-square' , 'name' => 'Envelope Square' );
		$icons[] = array( 'id' => 'wordpress' , 'name' => 'WordPress Logo' );
		$icons[] = array( 'id' => 'openid' , 'name' => 'OpenID' );
		$icons[] = array( 'id' => 'university' , 'name' => 'University' );
		$icons[] = array( 'id' => 'graduation-cap' , 'name' => 'Graduation Cap' );
		$icons[] = array( 'id' => 'yahoo' , 'name' => 'Yahoo Logo' );
		$icons[] = array( 'id' => 'google' , 'name' => 'Google Logo' );
		$icons[] = array( 'id' => 'reddit' , 'name' => 'reddit Logo' );
		$icons[] = array( 'id' => 'reddit-square' , 'name' => 'reddit Square' );
		$icons[] = array( 'id' => 'stumbleupon-circle' , 'name' => 'StumbleUpon Circle' );
		$icons[] = array( 'id' => 'stumbleupon' , 'name' => 'StumbleUpon Logo' );
		$icons[] = array( 'id' => 'delicious' , 'name' => 'Delicious Logo' );
		$icons[] = array( 'id' => 'digg' , 'name' => 'Digg Logo' );
		$icons[] = array( 'id' => 'pied-piper-pp' , 'name' => 'Pied Piper PP Logo (Old)' );
		$icons[] = array( 'id' => 'pied-piper-alt' , 'name' => 'Pied Piper Alternate Logo' );
		$icons[] = array( 'id' => 'drupal' , 'name' => 'Drupal Logo' );
		$icons[] = array( 'id' => 'joomla' , 'name' => 'Joomla Logo' );
		$icons[] = array( 'id' => 'language' , 'name' => 'Language' );
		$icons[] = array( 'id' => 'fax' , 'name' => 'Fax' );
		$icons[] = array( 'id' => 'building' , 'name' => 'Building' );
		$icons[] = array( 'id' => 'child' , 'name' => 'Child' );
		$icons[] = array( 'id' => 'paw' , 'name' => 'Paw' );
		$icons[] = array( 'id' => 'spoon' , 'name' => 'spoon' );
		$icons[] = array( 'id' => 'cube' , 'name' => 'Cube' );
		$icons[] = array( 'id' => 'cubes' , 'name' => 'Cubes' );
		$icons[] = array( 'id' => 'behance' , 'name' => 'Behance' );
		$icons[] = array( 'id' => 'behance-square' , 'name' => 'Behance Square' );
		$icons[] = array( 'id' => 'steam' , 'name' => 'Steam' );
		$icons[] = array( 'id' => 'steam-square' , 'name' => 'Steam Square' );
		$icons[] = array( 'id' => 'recycle' , 'name' => 'Recycle' );
		$icons[] = array( 'id' => 'car' , 'name' => 'Car' );
		$icons[] = array( 'id' => 'taxi' , 'name' => 'Taxi' );
		$icons[] = array( 'id' => 'tree' , 'name' => 'Tree' );
		$icons[] = array( 'id' => 'spotify' , 'name' => 'Spotify' );
		$icons[] = array( 'id' => 'deviantart' , 'name' => 'deviantART' );
		$icons[] = array( 'id' => 'soundcloud' , 'name' => 'SoundCloud' );
		$icons[] = array( 'id' => 'database' , 'name' => 'Database' );
		$icons[] = array( 'id' => 'file-pdf-o' , 'name' => 'PDF File Outlined' );
		$icons[] = array( 'id' => 'file-word-o' , 'name' => 'Word File Outlined' );
		$icons[] = array( 'id' => 'file-excel-o' , 'name' => 'Excel File Outlined' );
		$icons[] = array( 'id' => 'file-powerpoint-o' , 'name' => 'Powerpoint File Outlined' );
		$icons[] = array( 'id' => 'file-image-o' , 'name' => 'Image File Outlined' );
		$icons[] = array( 'id' => 'file-archive-o' , 'name' => 'Archive File Outlined' );
		$icons[] = array( 'id' => 'file-audio-o' , 'name' => 'Audio File Outlined' );
		$icons[] = array( 'id' => 'file-video-o' , 'name' => 'Video File Outlined' );
		$icons[] = array( 'id' => 'file-code-o' , 'name' => 'Code File Outlined' );
		$icons[] = array( 'id' => 'vine' , 'name' => 'Vine' );
		$icons[] = array( 'id' => 'codepen' , 'name' => 'Codepen' );
		$icons[] = array( 'id' => 'jsfiddle' , 'name' => 'jsFiddle' );
		$icons[] = array( 'id' => 'life-ring' , 'name' => 'Life Ring' );
		$icons[] = array( 'id' => 'circle-o-notch' , 'name' => 'Circle Outlined Notched' );
		$icons[] = array( 'id' => 'rebel' , 'name' => 'Rebel Alliance' );
		$icons[] = array( 'id' => 'empire' , 'name' => 'Galactic Empire' );
		$icons[] = array( 'id' => 'git-square' , 'name' => 'Git Square' );
		$icons[] = array( 'id' => 'git' , 'name' => 'Git' );
		$icons[] = array( 'id' => 'hacker-news' , 'name' => 'Hacker News' );
		$icons[] = array( 'id' => 'tencent-weibo' , 'name' => 'Tencent Weibo' );
		$icons[] = array( 'id' => 'qq' , 'name' => 'QQ' );
		$icons[] = array( 'id' => 'weixin' , 'name' => 'Weixin (WeChat)' );
		$icons[] = array( 'id' => 'paper-plane' , 'name' => 'Paper Plane' );
		$icons[] = array( 'id' => 'paper-plane-o' , 'name' => 'Paper Plane Outlined' );
		$icons[] = array( 'id' => 'history' , 'name' => 'History' );
		$icons[] = array( 'id' => 'circle-thin' , 'name' => 'Circle Outlined Thin' );
		$icons[] = array( 'id' => 'header' , 'name' => 'header' );
		$icons[] = array( 'id' => 'paragraph' , 'name' => 'paragraph' );
		$icons[] = array( 'id' => 'sliders' , 'name' => 'Sliders' );
		$icons[] = array( 'id' => 'share-alt' , 'name' => 'Share Alt' );
		$icons[] = array( 'id' => 'share-alt-square' , 'name' => 'Share Alt Square' );
		$icons[] = array( 'id' => 'bomb' , 'name' => 'Bomb' );
		$icons[] = array( 'id' => 'futbol-o' , 'name' => 'Futbol Outlined' );
		$icons[] = array( 'id' => 'tty' , 'name' => 'TTY' );
		$icons[] = array( 'id' => 'binoculars' , 'name' => 'Binoculars' );
		$icons[] = array( 'id' => 'plug' , 'name' => 'Plug' );
		$icons[] = array( 'id' => 'slideshare' , 'name' => 'Slideshare' );
		$icons[] = array( 'id' => 'twitch' , 'name' => 'Twitch' );
		$icons[] = array( 'id' => 'yelp' , 'name' => 'Yelp' );
		$icons[] = array( 'id' => 'newspaper-o' , 'name' => 'Newspaper Outlined' );
		$icons[] = array( 'id' => 'wifi' , 'name' => 'WiFi' );
		$icons[] = array( 'id' => 'calculator' , 'name' => 'Calculator' );
		$icons[] = array( 'id' => 'paypal' , 'name' => 'Paypal' );
		$icons[] = array( 'id' => 'google-wallet' , 'name' => 'Google Wallet' );
		$icons[] = array( 'id' => 'cc-visa' , 'name' => 'Visa Credit Card' );
		$icons[] = array( 'id' => 'cc-mastercard' , 'name' => 'MasterCard Credit Card' );
		$icons[] = array( 'id' => 'cc-discover' , 'name' => 'Discover Credit Card' );
		$icons[] = array( 'id' => 'cc-amex' , 'name' => 'American Express Credit Card' );
		$icons[] = array( 'id' => 'cc-paypal' , 'name' => 'Paypal Credit Card' );
		$icons[] = array( 'id' => 'cc-stripe' , 'name' => 'Stripe Credit Card' );
		$icons[] = array( 'id' => 'bell-slash' , 'name' => 'Bell Slash' );
		$icons[] = array( 'id' => 'bell-slash-o' , 'name' => 'Bell Slash Outlined' );
		$icons[] = array( 'id' => 'trash' , 'name' => 'Trash' );
		$icons[] = array( 'id' => 'copyright' , 'name' => 'Copyright' );
		$icons[] = array( 'id' => 'at' , 'name' => 'At' );
		$icons[] = array( 'id' => 'eyedropper' , 'name' => 'Eyedropper' );
		$icons[] = array( 'id' => 'paint-brush' , 'name' => 'Paint Brush' );
		$icons[] = array( 'id' => 'birthday-cake' , 'name' => 'Birthday Cake' );
		$icons[] = array( 'id' => 'area-chart' , 'name' => 'Area Chart' );
		$icons[] = array( 'id' => 'pie-chart' , 'name' => 'Pie Chart' );
		$icons[] = array( 'id' => 'line-chart' , 'name' => 'Line Chart' );
		$icons[] = array( 'id' => 'lastfm' , 'name' => 'last.fm' );
		$icons[] = array( 'id' => 'lastfm-square' , 'name' => 'last.fm Square' );
		$icons[] = array( 'id' => 'toggle-off' , 'name' => 'Toggle Off' );
		$icons[] = array( 'id' => 'toggle-on' , 'name' => 'Toggle On' );
		$icons[] = array( 'id' => 'bicycle' , 'name' => 'Bicycle' );
		$icons[] = array( 'id' => 'bus' , 'name' => 'Bus' );
		$icons[] = array( 'id' => 'ioxhost' , 'name' => 'ioxhost' );
		$icons[] = array( 'id' => 'angellist' , 'name' => 'AngelList' );
		$icons[] = array( 'id' => 'cc' , 'name' => 'Closed Captions' );
		$icons[] = array( 'id' => 'ils' , 'name' => 'Shekel (ILS)' );
		$icons[] = array( 'id' => 'meanpath' , 'name' => 'meanpath' );
		$icons[] = array( 'id' => 'buysellads' , 'name' => 'BuySellAds' );
		$icons[] = array( 'id' => 'connectdevelop' , 'name' => 'Connect Develop' );
		$icons[] = array( 'id' => 'dashcube' , 'name' => 'DashCube' );
		$icons[] = array( 'id' => 'forumbee' , 'name' => 'Forumbee' );
		$icons[] = array( 'id' => 'leanpub' , 'name' => 'Leanpub' );
		$icons[] = array( 'id' => 'sellsy' , 'name' => 'Sellsy' );
		$icons[] = array( 'id' => 'shirtsinbulk' , 'name' => 'Shirts in Bulk' );
		$icons[] = array( 'id' => 'simplybuilt' , 'name' => 'SimplyBuilt' );
		$icons[] = array( 'id' => 'skyatlas' , 'name' => 'skyatlas' );
		$icons[] = array( 'id' => 'cart-plus' , 'name' => 'Add to Shopping Cart' );
		$icons[] = array( 'id' => 'cart-arrow-down' , 'name' => 'Shopping Cart Arrow Down' );
		$icons[] = array( 'id' => 'diamond' , 'name' => 'Diamond' );
		$icons[] = array( 'id' => 'ship' , 'name' => 'Ship' );
		$icons[] = array( 'id' => 'user-secret' , 'name' => 'User Secret' );
		$icons[] = array( 'id' => 'motorcycle' , 'name' => 'Motorcycle' );
		$icons[] = array( 'id' => 'street-view' , 'name' => 'Street View' );
		$icons[] = array( 'id' => 'heartbeat' , 'name' => 'Heartbeat' );
		$icons[] = array( 'id' => 'venus' , 'name' => 'Venus' );
		$icons[] = array( 'id' => 'mars' , 'name' => 'Mars' );
		$icons[] = array( 'id' => 'mercury' , 'name' => 'Mercury' );
		$icons[] = array( 'id' => 'transgender' , 'name' => 'Transgender' );
		$icons[] = array( 'id' => 'transgender-alt' , 'name' => 'Transgender Alt' );
		$icons[] = array( 'id' => 'venus-double' , 'name' => 'Venus Double' );
		$icons[] = array( 'id' => 'mars-double' , 'name' => 'Mars Double' );
		$icons[] = array( 'id' => 'venus-mars' , 'name' => 'Venus Mars' );
		$icons[] = array( 'id' => 'mars-stroke' , 'name' => 'Mars Stroke' );
		$icons[] = array( 'id' => 'mars-stroke-v' , 'name' => 'Mars Stroke Vertical' );
		$icons[] = array( 'id' => 'mars-stroke-h' , 'name' => 'Mars Stroke Horizontal' );
		$icons[] = array( 'id' => 'neuter' , 'name' => 'Neuter' );
		$icons[] = array( 'id' => 'genderless' , 'name' => 'Genderless' );
		$icons[] = array( 'id' => 'facebook-official' , 'name' => 'Facebook Official' );
		$icons[] = array( 'id' => 'pinterest-p' , 'name' => 'Pinterest P' );
		$icons[] = array( 'id' => 'whatsapp' , 'name' => 'What\'s App' );
		$icons[] = array( 'id' => 'server' , 'name' => 'Server' );
		$icons[] = array( 'id' => 'user-plus' , 'name' => 'Add User' );
		$icons[] = array( 'id' => 'user-times' , 'name' => 'Remove User' );
		$icons[] = array( 'id' => 'bed' , 'name' => 'Bed' );
		$icons[] = array( 'id' => 'viacoin' , 'name' => 'Viacoin' );
		$icons[] = array( 'id' => 'train' , 'name' => 'Train' );
		$icons[] = array( 'id' => 'subway' , 'name' => 'Subway' );
		$icons[] = array( 'id' => 'medium' , 'name' => 'Medium' );
		$icons[] = array( 'id' => 'y-combinator' , 'name' => 'Y Combinator' );
		$icons[] = array( 'id' => 'optin-monster' , 'name' => 'Optin Monster' );
		$icons[] = array( 'id' => 'opencart' , 'name' => 'OpenCart' );
		$icons[] = array( 'id' => 'expeditedssl' , 'name' => 'ExpeditedSSL' );
		$icons[] = array( 'id' => 'battery-full' , 'name' => 'Battery Full' );
		$icons[] = array( 'id' => 'battery-three-quarters' , 'name' => 'Battery 3/4 Full' );
		$icons[] = array( 'id' => 'battery-half' , 'name' => 'Battery 1/2 Full' );
		$icons[] = array( 'id' => 'battery-quarter' , 'name' => 'Battery 1/4 Full' );
		$icons[] = array( 'id' => 'battery-empty' , 'name' => 'Battery Empty' );
		$icons[] = array( 'id' => 'mouse-pointer' , 'name' => 'Mouse Pointer' );
		$icons[] = array( 'id' => 'i-cursor' , 'name' => 'I Beam Cursor' );
		$icons[] = array( 'id' => 'object-group' , 'name' => 'Object Group' );
		$icons[] = array( 'id' => 'object-ungroup' , 'name' => 'Object Ungroup' );
		$icons[] = array( 'id' => 'sticky-note' , 'name' => 'Sticky Note' );
		$icons[] = array( 'id' => 'sticky-note-o' , 'name' => 'Sticky Note Outlined' );
		$icons[] = array( 'id' => 'cc-jcb' , 'name' => 'JCB Credit Card' );
		$icons[] = array( 'id' => 'cc-diners-club' , 'name' => 'Diner\'s Club Credit Card' );
		$icons[] = array( 'id' => 'clone' , 'name' => 'Clone' );
		$icons[] = array( 'id' => 'balance-scale' , 'name' => 'Balance Scale' );
		$icons[] = array( 'id' => 'hourglass-o' , 'name' => 'Hourglass Outlined' );
		$icons[] = array( 'id' => 'hourglass-start' , 'name' => 'Hourglass Start' );
		$icons[] = array( 'id' => 'hourglass-half' , 'name' => 'Hourglass Half' );
		$icons[] = array( 'id' => 'hourglass-end' , 'name' => 'Hourglass End' );
		$icons[] = array( 'id' => 'hourglass' , 'name' => 'Hourglass' );
		$icons[] = array( 'id' => 'hand-rock-o' , 'name' => 'Rock (Hand)' );
		$icons[] = array( 'id' => 'hand-paper-o' , 'name' => 'Paper (Hand)' );
		$icons[] = array( 'id' => 'hand-scissors-o' , 'name' => 'Scissors (Hand)' );
		$icons[] = array( 'id' => 'hand-lizard-o' , 'name' => 'Lizard (Hand)' );
		$icons[] = array( 'id' => 'hand-spock-o' , 'name' => 'Spock (Hand)' );
		$icons[] = array( 'id' => 'hand-pointer-o' , 'name' => 'Hand Pointer' );
		$icons[] = array( 'id' => 'hand-peace-o' , 'name' => 'Hand Peace' );
		$icons[] = array( 'id' => 'trademark' , 'name' => 'Trademark' );
		$icons[] = array( 'id' => 'registered' , 'name' => 'Registered Trademark' );
		$icons[] = array( 'id' => 'creative-commons' , 'name' => 'Creative Commons' );
		$icons[] = array( 'id' => 'gg' , 'name' => 'GG Currency' );
		$icons[] = array( 'id' => 'gg-circle' , 'name' => 'GG Currency Circle' );
		$icons[] = array( 'id' => 'tripadvisor' , 'name' => 'TripAdvisor' );
		$icons[] = array( 'id' => 'odnoklassniki' , 'name' => 'Odnoklassniki' );
		$icons[] = array( 'id' => 'odnoklassniki-square' , 'name' => 'Odnoklassniki Square' );
		$icons[] = array( 'id' => 'get-pocket' , 'name' => 'Get Pocket' );
		$icons[] = array( 'id' => 'wikipedia-w' , 'name' => 'Wikipedia W' );
		$icons[] = array( 'id' => 'safari' , 'name' => 'Safari' );
		$icons[] = array( 'id' => 'chrome' , 'name' => 'Chrome' );
		$icons[] = array( 'id' => 'firefox' , 'name' => 'Firefox' );
		$icons[] = array( 'id' => 'opera' , 'name' => 'Opera' );
		$icons[] = array( 'id' => 'internet-explorer' , 'name' => 'Internet-explorer' );
		$icons[] = array( 'id' => 'television' , 'name' => 'Television' );
		$icons[] = array( 'id' => 'contao' , 'name' => 'Contao' );
		$icons[] = array( 'id' => '500px' , 'name' => '500px' );
		$icons[] = array( 'id' => 'amazon' , 'name' => 'Amazon' );
		$icons[] = array( 'id' => 'calendar-plus-o' , 'name' => 'Calendar Plus Outlined' );
		$icons[] = array( 'id' => 'calendar-minus-o' , 'name' => 'Calendar Minus Outlined' );
		$icons[] = array( 'id' => 'calendar-times-o' , 'name' => 'Calendar Times Outlined' );
		$icons[] = array( 'id' => 'calendar-check-o' , 'name' => 'Calendar Check Outlined' );
		$icons[] = array( 'id' => 'industry' , 'name' => 'Industry' );
		$icons[] = array( 'id' => 'map-pin' , 'name' => 'Map Pin' );
		$icons[] = array( 'id' => 'map-signs' , 'name' => 'Map Signs' );
		$icons[] = array( 'id' => 'map-o' , 'name' => 'Map Outlined' );
		$icons[] = array( 'id' => 'map' , 'name' => 'Map' );
		$icons[] = array( 'id' => 'commenting' , 'name' => 'Commenting' );
		$icons[] = array( 'id' => 'commenting-o' , 'name' => 'Commenting Outlined' );
		$icons[] = array( 'id' => 'houzz' , 'name' => 'Houzz' );
		$icons[] = array( 'id' => 'vimeo' , 'name' => 'Vimeo' );
		$icons[] = array( 'id' => 'black-tie' , 'name' => 'Font Awesome Black Tie' );
		$icons[] = array( 'id' => 'fonticons' , 'name' => 'Fonticons' );
		$icons[] = array( 'id' => 'reddit-alien' , 'name' => 'reddit Alien' );
		$icons[] = array( 'id' => 'edge' , 'name' => 'Edge Browser' );
		$icons[] = array( 'id' => 'credit-card-alt' , 'name' => 'Credit Card' );
		$icons[] = array( 'id' => 'codiepie' , 'name' => 'Codie Pie' );
		$icons[] = array( 'id' => 'modx' , 'name' => 'MODX' );
		$icons[] = array( 'id' => 'fort-awesome' , 'name' => 'Fort Awesome' );
		$icons[] = array( 'id' => 'usb' , 'name' => 'USB' );
		$icons[] = array( 'id' => 'product-hunt' , 'name' => 'Product Hunt' );
		$icons[] = array( 'id' => 'mixcloud' , 'name' => 'Mixcloud' );
		$icons[] = array( 'id' => 'scribd' , 'name' => 'Scribd' );
		$icons[] = array( 'id' => 'pause-circle' , 'name' => 'Pause Circle' );
		$icons[] = array( 'id' => 'pause-circle-o' , 'name' => 'Pause Circle Outlined' );
		$icons[] = array( 'id' => 'stop-circle' , 'name' => 'Stop Circle' );
		$icons[] = array( 'id' => 'stop-circle-o' , 'name' => 'Stop Circle Outlined' );
		$icons[] = array( 'id' => 'shopping-bag' , 'name' => 'Shopping Bag' );
		$icons[] = array( 'id' => 'shopping-basket' , 'name' => 'Shopping Basket' );
		$icons[] = array( 'id' => 'hashtag' , 'name' => 'Hashtag' );
		$icons[] = array( 'id' => 'bluetooth' , 'name' => 'Bluetooth' );
		$icons[] = array( 'id' => 'bluetooth-b' , 'name' => 'Bluetooth' );
		$icons[] = array( 'id' => 'percent' , 'name' => 'Percent' );
		$icons[] = array( 'id' => 'gitlab' , 'name' => 'GitLab' );
		$icons[] = array( 'id' => 'wpbeginner' , 'name' => 'WPBeginner' );
		$icons[] = array( 'id' => 'wpforms' , 'name' => 'WPForms' );
		$icons[] = array( 'id' => 'envira' , 'name' => 'Envira Gallery' );
		$icons[] = array( 'id' => 'universal-access' , 'name' => 'Universal Access' );
		$icons[] = array( 'id' => 'wheelchair-alt' , 'name' => 'Wheelchair Alt' );
		$icons[] = array( 'id' => 'question-circle-o' , 'name' => 'Question Circle Outlined' );
		$icons[] = array( 'id' => 'blind' , 'name' => 'Blind' );
		$icons[] = array( 'id' => 'audio-description' , 'name' => 'Audio Description' );
		$icons[] = array( 'id' => 'volume-control-phone' , 'name' => 'Volume Control Phone' );
		$icons[] = array( 'id' => 'braille' , 'name' => 'Braille' );
		$icons[] = array( 'id' => 'assistive-listening-systems' , 'name' => 'Assistive Listening Systems' );
		$icons[] = array( 'id' => 'american-sign-language-interpreting' , 'name' => 'American Sign Language Interpreting' );
		$icons[] = array( 'id' => 'deaf' , 'name' => 'Deaf' );
		$icons[] = array( 'id' => 'glide' , 'name' => 'Glide' );
		$icons[] = array( 'id' => 'glide-g' , 'name' => 'Glide G' );
		$icons[] = array( 'id' => 'sign-language' , 'name' => 'Sign Language' );
		$icons[] = array( 'id' => 'low-vision' , 'name' => 'Low Vision' );
		$icons[] = array( 'id' => 'viadeo' , 'name' => 'Viadeo' );
		$icons[] = array( 'id' => 'viadeo-square' , 'name' => 'Viadeo Square' );
		$icons[] = array( 'id' => 'snapchat' , 'name' => 'Snapchat' );
		$icons[] = array( 'id' => 'snapchat-ghost' , 'name' => 'Snapchat Ghost' );
		$icons[] = array( 'id' => 'snapchat-square' , 'name' => 'Snapchat Square' );
		$icons[] = array( 'id' => 'pied-piper' , 'name' => 'Pied Piper Logo' );
		$icons[] = array( 'id' => 'first-order' , 'name' => 'First Order' );
		$icons[] = array( 'id' => 'yoast' , 'name' => 'Yoast' );
		$icons[] = array( 'id' => 'themeisle' , 'name' => 'ThemeIsle' );
		$icons[] = array( 'id' => 'google-plus-official' , 'name' => 'Google Plus Official' );
		$icons[] = array( 'id' => 'font-awesome' , 'name' => 'Font Awesome' );
		$icons[] = array( 'id' => 'handshake-o' , 'name' => 'Handshake Outlined' );
		$icons[] = array( 'id' => 'envelope-open' , 'name' => 'Envelope Open' );
		$icons[] = array( 'id' => 'envelope-open-o' , 'name' => 'Envelope Open Outlined' );
		$icons[] = array( 'id' => 'linode' , 'name' => 'Linode' );
		$icons[] = array( 'id' => 'address-book' , 'name' => 'Address Book' );
		$icons[] = array( 'id' => 'address-book-o' , 'name' => 'Address Book Outlined' );
		$icons[] = array( 'id' => 'address-card' , 'name' => 'Address Card' );
		$icons[] = array( 'id' => 'address-card-o' , 'name' => 'Address Card Outlined' );
		$icons[] = array( 'id' => 'user-circle' , 'name' => 'User Circle' );
		$icons[] = array( 'id' => 'user-circle-o' , 'name' => 'User Circle Outlined' );
		$icons[] = array( 'id' => 'user-o' , 'name' => 'User Outlined' );
		$icons[] = array( 'id' => 'id-badge' , 'name' => 'Identification Badge' );
		$icons[] = array( 'id' => 'id-card' , 'name' => 'Identification Card' );
		$icons[] = array( 'id' => 'id-card-o' , 'name' => 'Identification Card Outlined' );
		$icons[] = array( 'id' => 'quora' , 'name' => 'Quora' );
		$icons[] = array( 'id' => 'free-code-camp' , 'name' => 'Free Code Camp' );
		$icons[] = array( 'id' => 'telegram' , 'name' => 'Telegram' );
		$icons[] = array( 'id' => 'thermometer-full' , 'name' => 'Thermometer Full' );
		$icons[] = array( 'id' => 'thermometer-three-quarters' , 'name' => 'Thermometer 3/4 Full' );
		$icons[] = array( 'id' => 'thermometer-half' , 'name' => 'Thermometer 1/2 Full' );
		$icons[] = array( 'id' => 'thermometer-quarter' , 'name' => 'Thermometer 1/4 Full' );
		$icons[] = array( 'id' => 'thermometer-empty' , 'name' => 'Thermometer Empty' );
		$icons[] = array( 'id' => 'shower' , 'name' => 'Shower' );
		$icons[] = array( 'id' => 'bath' , 'name' => 'Bath' );
		$icons[] = array( 'id' => 'podcast' , 'name' => 'Podcast' );
		$icons[] = array( 'id' => 'window-maximize' , 'name' => 'Window Maximize' );
		$icons[] = array( 'id' => 'window-minimize' , 'name' => 'Window Minimize' );
		$icons[] = array( 'id' => 'window-restore' , 'name' => 'Window Restore' );
		$icons[] = array( 'id' => 'window-close' , 'name' => 'Window Close' );
		$icons[] = array( 'id' => 'window-close-o' , 'name' => 'Window Close Outline' );
		$icons[] = array( 'id' => 'bandcamp' , 'name' => 'Bandcamp' );
		$icons[] = array( 'id' => 'grav' , 'name' => 'Grav' );
		$icons[] = array( 'id' => 'etsy' , 'name' => 'Etsy' );
		$icons[] = array( 'id' => 'imdb' , 'name' => 'IMDB' );
		$icons[] = array( 'id' => 'ravelry' , 'name' => 'Ravelry' );
		$icons[] = array( 'id' => 'eercast' , 'name' => 'Eercast' );
		$icons[] = array( 'id' => 'microchip' , 'name' => 'Microchip' );
		$icons[] = array( 'id' => 'snowflake-o' , 'name' => 'Snowflake Outlined' );
		$icons[] = array( 'id' => 'superpowers' , 'name' => 'Superpowers' );
		$icons[] = array( 'id' => 'wpexplorer' , 'name' => 'WPExplorer' );
		$icons[] = array( 'id' => 'meetup' , 'name' => 'Meetup' );

		return $icons;
	}
}
